modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU AGPL 3.0"

[[mods]] #mandatory
modId="skylanterns" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Skylanterns" #mandatory
#logoFile="skylanterns.png" #optional
authors="cnlimiter" #optional
# The description text for the mod (multi line!) (#mandatory)
description='''
Traditional Chinese Sky Lanterns
'''
[[dependencies.skylanterns]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[36,)" #mandatory
   ordering="NONE"
   side="BOTH"
[[dependencies.skylanterns]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.16.5,1.17)"
   ordering="NONE"
   side="BOTH"
